# Group Banco
## Listagem [/Bank/All]
### Listagem [GET]
- Rota que lista todos os bancos na tela de cadastro de reembolsos.
+ Request (application/json)
    
	+ Body 
		No Body

+ Response 200 (application/json)

	+ Body
    [
      {
        "id": 31,
        "desc_bank": "ITAU UNICLASS"
      },
      {
        "id": 32,
        "desc_bank": "BANCO DO BRASIL"
      },
      {
        "id": 33,
        "desc_bank": "SANTANDER"
      }
    ]