# Group Departamento
## Listagem [/Departament/All]
### Listagem [GET]
- Rota que lista todos os departamentos na tela de cadastro de reembolsos.
+ Request (application/json)
    
	+ Body 
		No Body

+ Response 200 (application/json)

	+ Body
    [
      {
        "id": 1,
        "desc_departament": "TECNOLOGIA DA INFORMAÇÃO"
      },
      {
        "id": 2,
        "desc_departament": "RECURSOS HUMANOS"
      },
      {
        "id": 3,
        "desc_departament": "FINANCEIRO"
      }
    ]