FORMAT: 1A
# Reebolso Fácil
Descrição
- Documentação da API, usada como Backend da aplicação Reembolso Fácil.
- Você pode realizar testes com cada uma das rotas para consumir a API. 

<!-- include(user.apib) -->
<!-- include(refund.apib) -->
<!-- include(bank.apib) -->
<!-- include(departament.apib) -->
<!-- include(typeRefund.apib) -->
